language: python
python:
  - "3.6"
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm web sh -c "python manage.py wait_for_db --settings=app.settings.development && python manage.py test --settings=app.settings.development && flake8"