# Generated by Django 3.2.5 on 2021-07-20 18:32

import apps.common.utils.validators
import apps.media.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNSURE', 'UNSURE')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('file', models.ImageField(null=True, upload_to=apps.media.models.image_file_path, validators=[apps.common.utils.validators.validate_image_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('estimated_length_in_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(null=True)),
                ('album_type', models.CharField(blank=True, choices=[('ALBUM', 'ALBUM'), ('SINGLE', 'SINGLE'), ('COMPILATION', 'COMPILATION')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('UNPUBLISHED', 'UNPUBLISHED'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED'), ('TRASHED', 'TRASHED')], max_length=15, null=True)),
                ('authors', models.ManyToManyField(to='media.Author')),
                ('genres', models.ManyToManyField(to='media.Genre')),
                ('images', models.ManyToManyField(to='media.Image')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.language')),
                ('media_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.format')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.PositiveIntegerField()),
                ('file_url', models.FileField(null=True, upload_to=apps.media.models.track_file_path, validators=[apps.common.utils.validators.validate_file_type])),
                ('duration', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sample', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField()),
                ('medias', models.ManyToManyField(blank=True, to='media.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sequence', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNSURE', 'UNSURE')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='narrators',
            field=models.ManyToManyField(to='media.Narrator'),
        ),
        migrations.AddField(
            model_name='media',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='media.Track'),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('width', models.PositiveIntegerField()),
                ('watermark', models.BooleanField()),
                ('logo_max_width_height_ratio', models.FloatField(default=0.06)),
                ('logo_top_left_ratio', models.FloatField(default=0.02)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-width'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.imagesize'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(to='media.Image'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
