# Generated by Django 2.2.24 on 2021-06-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNSURE', 'UNSURE')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='authors',
        ),
        migrations.AddField(
            model_name='media',
            name='authors',
            field=models.ManyToManyField(to='media.Author'),
        ),
    ]
