# Generated by Django 2.2.24 on 2021-06-19 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesize',
            options={'ordering': ['-width']},
        ),
        migrations.AddField(
            model_name='imagesize',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
