# Generated by Django 2.2.18 on 2021-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
