# Generated by Django 2.2.24 on 2021-06-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210619_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='file',
        ),
    ]
