# Generated by Django 2.2.18 on 2021-02-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_track_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='popularity',
            new_name='rating',
        ),
    ]
