# Generated by Django 2.2.18 on 2021-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20210222_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='authors',
            field=models.CharField(default='Belendia', max_length=255),
            preserve_default=False,
        ),
    ]
