# Generated by Django 2.2.24 on 2021-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20210619_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-sequence', '-id']},
        ),
        migrations.AddField(
            model_name='track',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
