# Generated by Django 3.2.5 on 2021-08-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='media_like',
        ),
    ]
