# Generated by Django 2.2.18 on 2021-03-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='duration_ms',
            new_name='duration',
        ),
    ]
