# Generated by Django 2.2.24 on 2021-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210621_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='medias',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='media.Track'),
        ),
    ]
