# Generated by Django 3.2.5 on 2021-08-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20210803_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='rating',
        ),
    ]
