# Generated by Django 2.2.24 on 2021-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20210624_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('UNPUBLISHED', 'UNPUBLISHED'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED'), ('TRASHED', 'TRASHED')], default='UNPUBLISHED', max_length=15),
        ),
    ]
