# Generated by Django 2.2.24 on 2021-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('UNPUBLISHED', 'UNPUBLISHED'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED'), ('TRASHED', 'TRASHED')], max_length=15, null=True),
        ),
    ]
