# Generated by Django 2.2.24 on 2021-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_phoneverification_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='sent_at',
            field=models.DateTimeField(verbose_name='Security Code Sent At'),
        ),
    ]
