# Generated by Django 2.2.15 on 2020-09-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
