# Generated by Django 2.2.15 on 2020-09-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(choices=[('ALBUM', 'ALBUM'), ('SINGLE', 'SINGLE'), ('COMPILATION', 'COMPILATION')], max_length=20)),
                ('estimated_length_in_seconds', models.PositiveIntegerField()),
                ('popularity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='core.Genre')),
                ('tracks', models.ManyToManyField(to='core.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
