# Generated by Django 2.2.15 on 2020-09-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200906_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='audiobook',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-id']},
        ),
    ]
