# Generated by Django 2.2.15 on 2020-09-11 10:12

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200910_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(null=True, upload_to=core.models.media_image_file_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('estimated_length_in_seconds', models.PositiveIntegerField(null=True)),
                ('popularity', models.PositiveIntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('ALBUM', 'ALBUM'), ('AUDIOBOOK', 'AUDIOBOOK'), ('PODCAST', 'PODCAST'), ('NEWSPAPER', 'NEWSPAPER'), ('MAGAZINE', 'MAGAZINE')], max_length=20, null=True)),
                ('word_count', models.PositiveIntegerField(null=True)),
                ('album_type', models.CharField(choices=[('ALBUM', 'ALBUM'), ('SINGLE', 'SINGLE'), ('COMPILATION', 'COMPILATION')], max_length=20, null=True)),
                ('genres', models.ManyToManyField(to='core.Genre')),
                ('tracks', models.ManyToManyField(to='core.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
    ]
