# Generated by Django 2.2.15 on 2020-09-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200911_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media_type',
            new_name='media_format',
        ),
    ]
