# Generated by Django 2.2.15 on 2020-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200911_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_format',
            field=models.CharField(choices=[('ALBUM', 'ALBUM'), ('AUDIOBOOK', 'AUDIOBOOK'), ('PODCAST', 'PODCAST'), ('NEWSPAPER', 'NEWSPAPER'), ('MAGAZINE', 'MAGAZINE')], default='AUDIOBOOK', max_length=20),
            preserve_default=False,
        ),
    ]
