# Generated by Django 2.2.15 on 2020-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200911_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_format',
            field=models.CharField(choices=[('ALBUM', 'ALBUM'), ('AUDIOBOOK', 'AUDIOBOOK'), ('PODCAST', 'PODCAST'), ('NEWSPAPER', 'NEWSPAPER'), ('MAGAZINE', 'MAGAZINE'), ('RADIO', 'RADIO'), ('SPEECH', 'SPEECH'), ('INTERVIEW', 'INTERVIEW'), ('LECTURE', 'LECTURE')], max_length=20),
        ),
    ]
