# Generated by Django 2.2.15 on 2020-09-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200912_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='album_type',
            field=models.CharField(blank=True, choices=[('ALBUM', 'ALBUM'), ('SINGLE', 'SINGLE'), ('COMPILATION', 'COMPILATION')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='estimated_length_in_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
