# Generated by Django 2.2.15 on 2020-09-23 08:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200916_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='original_url',
        ),
        migrations.AddField(
            model_name='track',
            name='file_url',
            field=models.FileField(null=True, upload_to=core.models.track_file_path),
        ),
    ]
