# Generated by Django 2.2.15 on 2020-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200923_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='media_list', to='core.Track'),
        ),
    ]
