# Generated by Django 2.2.15 on 2020-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201002_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
