# Generated by Django 2.2.15 on 2020-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200912_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermedia',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
