# Generated by Django 2.2.15 on 2020-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_coupon_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
