# Generated by Django 2.2.15 on 2020-09-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200918_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermedia',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
