# Generated by Django 2.2.15 on 2020-09-18 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_ordermedia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedia',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
